apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress-srv
spec:
  rules:
    - http:
        paths:
          - path: /Robot
            pathType: Prefix
            backend:
              service:
                name: robotservice-clusterip-srv
                port:
                  number: 80
          - path: /Drone
            pathType: Prefix
            backend:
              service:
                name: droneservice-clusterip-srv
                port:
                  number: 80